version: '3.8'
services:
  database:
    container_name: database
    image: postgres:14.1
    command: [ "postgres", "-c", "log_statement=all" ]
    volumes:
      - ./postgresqldb:/var/lib/postgresql/data
    ports:
      - 5599:5432
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234

  php:
    container_name: php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - database

  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - php
      - database