version: '3.8'
services:

  gateway:
    container_name: gateway
    build:
      context: docker/gateway
    ports:
      - '8080:80'
    depends_on:
      - frontend
      - api

  frontend:
    container_name: frontend
    build:
      context: docker/frontend/nginx
    depends_on:
      - node

  node:
    container_name: node
    build:
      context: docker/frontend/node
    volumes:
      - ./frontend:/app
    tty: true

  frontend-cli:
    container_name: frontend-cli
    build:
      context: docker/frontend/cli
    volumes:
      - ./frontend:/app
    tty: true

  api:
    container_name: api
    build:
      context: docker/api/nginx
    ports:
      - '8081:80'
    volumes:
      - ./api:/var/www/symfony_docker
    depends_on:
      - php
      - database

  php:
    container_name: php
    build:
      context: docker/api/php
    volumes:
      - ./api:/var/www/symfony_docker
      - ./api/php.dev.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - database

  api-cli:
    container_name: api-cli
    build:
      context: docker/api/cli
    volumes:
      - ./api:/var/www/symfony_docker
      - ./api/php.dev.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - database
    tty: true

  database:
    container_name: database
    image: postgres:14.1
    command: [ "postgres", "-c", "log_statement=all" ]
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5599:5432'
    environment:
      - POSTGRES_DB=abs
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234

volumes:
  db_data: