framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'appointment-booking-service@yandex.ru'
        headers:
            From: 'ABS <appointment-booking-service@yandex.ru>'
